server:
    port: 0.0.0.0:8080

es:
  host: http://192.168.1.110:9200
  index: ""
  username: ""
  password: ""
  shards: ""
  replicas: ""
  sniff: false
  healthCheck: true
  infoLog: ""
  errorLog: ""
  traceLog: ""
